[package]
name = "rugst"
version = "0.1.8"
edition = "2024"

[dependencies]
rusqlite = { version = "0.40.2", features = ["bundled"] }
anyhow = "1.0.103"
fastembed = {
    version = "5.17.4",
    default-features = false,
    features = [
        "hf-hub",
        "ort-download-binaries-rustls-tls",
    ]
}

[lib]
name = "rugst"
crate-type = ["rlib", "cdylib"]