name: Build macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: rugst-macos
          path: target/release/*.dylib