name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and Pack
      run: dotnet pack dotnet/Rugst.NET/Rugst.NET.csproj -c Release -o ./nupkg

    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json